name: publish to ghcr
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  push:
    name: "Create build and push to GHCR"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      - id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository_owner }}
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          #TODO: Fix GitHub Actions Building?
          #platforms: linux/arm/v7,linux/amd64
          platforms: linux/amd64,linux/arm/v7,linux/arm/v8
          push: true
          tags: |
            ghcr.io/${{ steps.string.outputs.lowercase }}/g5api:latest

